# nixpacks.toml

[phases.setup]
nixPkgs = ['...', 'libreoffice']

[phases.build]
cmds = [
    '...',
    'which soffice || echo "soffice not found"',
    'ls -la $(which soffice)',
    'ldd $(which soffice)'
]