export type ThreadTypeModel =
  | 'mcqDirectHardThreadId'
  | 'mcqDirectMediumThreadId'
  | 'mcqDirectEasyThreadId'
  | 'mcqUseCaseHardThreadId'
  | 'mcqUseCaseMediumThreadId'
  | 'mcqUseCaseEasyThreadId'
  | 'flashCardHardThreadId'
  | 'flashCardMediumThreadId'
  | 'flashCardEasyThreadId'
  | 'documentChatThreadId'
  | 'multipleTrueFalseHardThreadId'
  | 'multipleTrueFalseMediumThreadId'
  | 'multipleTrueFalseEasyThreadId'
  | 'oralQuestionThreadId';
