export interface Config {
  openAiApiKey: string;
  port: string;
  databasePort: number;
  databaseUsername: string;
  databasePassword: string;
  database: string;
  databaseHost: string;
  jwtSecret: string;
  assistantIdFreePlan: string;
  assistantIdPaidPlan: string;
  topicExtractionAssistantId: string;
  documentSummarizationAssistantId: string;
  googleClientId: string;
  googleClientSecret: string;
  googleCallbackUrl: string;
  googleApiKey: string;
  googleSearchEngineId: string;
  frontendBaseUrl: string;
  frontendAccessTokenKey: string;
  mailChimpApiKey: string;
  mailChimpServerPrefix: string;
  mailChimpAudienceId: string;
  floDeskBaseUrl: string;
  floDeskApiKey: string;
  flutterwaveSecretKey: string;
  paystackSecretKey: string;
  emailUser: string;
  emailPass: string;
  emailHost: string;
  ipStackApiKey: string;
  ipInfoToken: string;
  iLovePdfPublicKey: string;
  firebaseAndroidOAuthClientId: string;
  firebaseIOSOAuthClientId: string;
  vapiPrivateKey: string;
  twilioAccountSID: string;
  twilioAuthToken: string;
  twilioPhoneNumber: string;
  pineconeApiKey: string;
  mistralApiKey: string;
  youtubeApiKey: string;
  rapidApiKey: string;
  asposeClientId: string;
  asposeClientSecret: string;
  geminiApiKey: string;
  adminEmail: string;
}

export default (): Config => ({
  openAiApiKey: process.env.OPEN_AI_API_KEY,
  port: process.env.PORT,
  databasePort: process.env.Database_Port as unknown as number,
  databaseUsername: process.env.Database_Username,
  databasePassword: process.env.Database_Password,
  database: process.env.Database,
  databaseHost: process.env.Database_Host,
  jwtSecret: process.env.JWT_SECRET,
  floDeskBaseUrl: process.env.FLO_DESK_BASE_URL,
  floDeskApiKey: process.env.FLO_DESK_API_KEY,
  assistantIdFreePlan: process.env.OPEN_AI_ASSITANT_ID_FREE_PLAN,
  assistantIdPaidPlan: process.env.OPEN_AI_ASSITANT_ID_PAID_PLAN,
  topicExtractionAssistantId: process.env.OPEN_AI_TOPIC_EXTRACTION_ASSISTANT,
  documentSummarizationAssistantId:
    process.env.OPEN_AI_DOCUMENT_SUMMARIZATION_ASSISTANT,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleCallbackUrl: process.env.GOOGLE_CALLBACK_URL,
  googleApiKey: process.env.GOOGLE_API_KEY,
  googleSearchEngineId: process.env.GOOGLE_SEARCH_ENGINE_ID,
  frontendBaseUrl: process.env.FRONTEND_BASE_URL,
  frontendAccessTokenKey: process.env.FRONTEND_ACCESS_TOKEN_KEY,
  mailChimpApiKey: process.env.MAILCHIMP_API_KEY,
  mailChimpServerPrefix: process.env.MAILCHIMP_SERVER_PREFIX,
  mailChimpAudienceId: process.env.MAILCHIMP_AUDIENCE_ID,
  flutterwaveSecretKey: process.env.FLUTTERWAVE_SECRET_KEY,
  paystackSecretKey: process.env.PAYSTACK_SECRET_KEY,
  emailPass: process.env.Email_pass,
  emailUser: process.env.Email_user,
  emailHost: process.env.Email_host,
  ipStackApiKey: process.env.IP_STACK_API_KEY,
  ipInfoToken: process.env.IP_INFO_TOKEN,
  iLovePdfPublicKey: process.env.ILOVEPDF_PUBLIC_KEY,
  firebaseAndroidOAuthClientId: process.env.FIREBASE_ANDROID_OAUTH_CLIENT_ID,
  firebaseIOSOAuthClientId: process.env.FIREBASE_IOS_OAUTH_CLIENT_ID,
  vapiPrivateKey: process.env.VAPI_PRIVATE_KEY,
  twilioAccountSID: process.env.TWILIO_ACCOUNT_SID,
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN,
  twilioPhoneNumber: process.env.TWILIO_PHONE_NUMBER,
  pineconeApiKey: process.env.PINECONE_KEY,
  mistralApiKey: process.env.MISTRAL_API_KEY,
  youtubeApiKey: process.env.YOUTUBE_API_KEY,
  rapidApiKey: process.env.RAPID_API_KEY,
  asposeClientId: process.env.ASPOSE_CLIENT_ID,
  asposeClientSecret: process.env.ASPOSE_CLIENT_SECRET,
  geminiApiKey: process.env.GEMINI_API_KEY,
  adminEmail: process.env.ADMIN_EMAIL
});
